// File generated by FlutterFire CLI.
// TODO: Run `flutterfire configure` for com.zuru.app to regenerate this file
//       with the correct Firebase app IDs and iosBundleId.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:zuru/config/env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace appId values after running `flutterfire configure` for com.zuru.app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.fbAndroidApiKey,
    appId: '1:613167220460:android:bbe16ac5538dcde4cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.fbIosApiKey,
    appId: '1:613167220460:ios:2ba400c3d91bb507cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
    androidClientId:
        '613167220460-83eurqic5dvqp6jcd9pt179ug8p8f49b.apps.googleusercontent.com',
    iosClientId:
        '613167220460-kstg329ehj3d5fq3fi57v4vtif5qs35g.apps.googleusercontent.com',
    iosBundleId: 'com.zuru.app',
  );
}
