// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:zuru/config/env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.fbAndroidApiKey,
    appId: '1:613167220460:android:ddde93633c1827c4cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.fbIosApiKey,
    appId: '1:613167220460:ios:da2a39d98273b040cdc7c9',
    messagingSenderId: '613167220460',
    projectId: 'unseen-e3b13',
    storageBucket: 'unseen-e3b13.firebasestorage.app',
    androidClientId:
        '613167220460-1am7911tc7eb6t8cbu690mvm1jregn0r.apps.googleusercontent.com',
    iosClientId:
        '613167220460-5p9pqltmr1eltgu7nlvigsqm77rof2e5.apps.googleusercontent.com',
    iosBundleId: 'com.zuru.ios',
  );
}
