// Mocks generated by Mockito 5.4.6 from annotations
// in zuru/test/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:supabase_flutter/supabase_flutter.dart' as _i4;
import 'package:zuru/core/entities/profile.entity.dart' as _i16;
import 'package:zuru/core/entities/user.entity.dart' as _i3;
import 'package:zuru/core/types/repo_reponse.type.dart' as _i7;
import 'package:zuru/modules/auth/data/models/auth.inputs.dart' as _i8;
import 'package:zuru/modules/auth/data/models/scout_profile.input.dart' as _i9;
import 'package:zuru/modules/auth/data/sources/remote_auth_datasource.dart'
    as _i20;
import 'package:zuru/modules/auth/domain/repository/auth_repository.dart'
    as _i5;
import 'package:zuru/modules/missions/data/models/enum.dart' as _i18;
import 'package:zuru/modules/missions/data/models/live_request.input.dart'
    as _i13;
import 'package:zuru/modules/missions/data/models/mission.inputs.dart' as _i12;
import 'package:zuru/modules/missions/data/sources/remote_missions_datasource.dart'
    as _i21;
import 'package:zuru/modules/missions/domain/entities/mission.entity.dart'
    as _i11;
import 'package:zuru/modules/missions/domain/entities/nearby_scout.entity.dart'
    as _i14;
import 'package:zuru/modules/missions/domain/entities/session.entity.dart'
    as _i15;
import 'package:zuru/modules/missions/domain/repository/missions_repository.dart'
    as _i10;
import 'package:zuru/modules/rating/domain/entities/rating.entity.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_2 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_3 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_4 extends _i1.SmartFake implements _i4.User {
  _FakeUser_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_5 extends _i1.SmartFake implements _i4.Session {
  _FakeSession_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>> login(_i8.LoginInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#login, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
              _FakeEither_0<_i7.ApiFail, _i3.User>(
                this,
                Invocation.method(#login, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
                  _FakeEither_0<_i7.ApiFail, _i3.User>(
                    this,
                    Invocation.method(#login, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>> loginWithOAuth(
    _i8.OAuthInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithOAuth, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
              _FakeEither_0<_i7.ApiFail, _i3.User>(
                this,
                Invocation.method(#loginWithOAuth, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
                  _FakeEither_0<_i7.ApiFail, _i3.User>(
                    this,
                    Invocation.method(#loginWithOAuth, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>> signup(
    _i8.SignupInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
              _FakeEither_0<_i7.ApiFail, _i3.User>(
                this,
                Invocation.method(#signup, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
                  _FakeEither_0<_i7.ApiFail, _i3.User>(
                    this,
                    Invocation.method(#signup, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>> verifyEmailOtp(
    _i8.VerifyOtpInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailOtp, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
              _FakeEither_0<_i7.ApiFail, _i3.User>(
                this,
                Invocation.method(#verifyEmailOtp, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
                  _FakeEither_0<_i7.ApiFail, _i3.User>(
                    this,
                    Invocation.method(#verifyEmailOtp, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> setupPhone(
    _i8.PhoneSetupInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setupPhone, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#setupPhone, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#setupPhone, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>> verifyPhoneOtp(
    _i8.VerifyOtpInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneOtp, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
              _FakeEither_0<_i7.ApiFail, _i3.User>(
                this,
                Invocation.method(#verifyPhoneOtp, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>.value(
                  _FakeEither_0<_i7.ApiFail, _i3.User>(
                    this,
                    Invocation.method(#verifyPhoneOtp, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i3.User>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> setupNames(_i8.NamesInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#setupNames, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#setupNames, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#setupNames, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> updateScoutProfile(
    _i9.ScoutProfileInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateScoutProfile, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#updateScoutProfile, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#updateScoutProfile, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#logout, []),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> sendPasswordResetOtp(
    _i8.ResetPasswordInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetOtp, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#sendPasswordResetOtp, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#sendPasswordResetOtp, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> sendPasswordResetEmail(
    _i8.ResetPasswordInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#sendPasswordResetEmail, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#sendPasswordResetEmail, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> verifyPasswordResetOtp(
    _i8.VerifyOtpInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetOtp, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#verifyPasswordResetOtp, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#verifyPasswordResetOtp, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, bool>> updatePassword(
    _i8.UpdatePasswordInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
              _FakeEither_0<_i7.ApiFail, bool>(
                this,
                Invocation.method(#updatePassword, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, bool>>.value(
                  _FakeEither_0<_i7.ApiFail, bool>(
                    this,
                    Invocation.method(#updatePassword, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, bool>>);
}

/// A class which mocks [MissionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMissionsRepository extends _i1.Mock
    implements _i10.MissionsRepository {
  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>> postMission(
    _i12.PostMissionInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postMission, [input]),
            returnValue:
                _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>.value(
                  _FakeEither_0<_i7.ApiFail, _i11.MissionEntity>(
                    this,
                    Invocation.method(#postMission, [input]),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>.value(
                  _FakeEither_0<_i7.ApiFail, _i11.MissionEntity>(
                    this,
                    Invocation.method(#postMission, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>> createLiveRequest(
    _i13.LiveRequestInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLiveRequest, [input]),
            returnValue:
                _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>.value(
                  _FakeEither_0<_i7.ApiFail, _i11.MissionEntity>(
                    this,
                    Invocation.method(#createLiveRequest, [input]),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>.value(
                  _FakeEither_0<_i7.ApiFail, _i11.MissionEntity>(
                    this,
                    Invocation.method(#createLiveRequest, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, _i11.MissionEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>
  getMyMissions() =>
      (super.noSuchMethod(
            Invocation.method(#getMyMissions, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i11.MissionEntity>>(
                    this,
                    Invocation.method(#getMyMissions, []),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i11.MissionEntity>>(
                    this,
                    Invocation.method(#getMyMissions, []),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, List<_i14.NearbyScout>>> getNearbyScouts({
    required double? latitude,
    required double? longitude,
    required double? radiusKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyScouts, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
            }),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i14.NearbyScout>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i14.NearbyScout>>(
                    this,
                    Invocation.method(#getNearbyScouts, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i14.NearbyScout>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i14.NearbyScout>>(
                    this,
                    Invocation.method(#getNearbyScouts, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #radiusKm: radiusKm,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, List<_i14.NearbyScout>>>);

  @override
  _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>
  watchActiveMissions() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveMissions, []),
            returnValue:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
            returnValueForMissingStub:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
          )
          as _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>);

  @override
  _i6.Stream<_i2.Either<_i7.ApiFail, _i15.SessionEntity>> watchLiveSession(
    List<String>? missions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLiveSession, [missions]),
            returnValue:
                _i6.Stream<_i2.Either<_i7.ApiFail, _i15.SessionEntity>>.empty(),
            returnValueForMissingStub:
                _i6.Stream<_i2.Either<_i7.ApiFail, _i15.SessionEntity>>.empty(),
          )
          as _i6.Stream<_i2.Either<_i7.ApiFail, _i15.SessionEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>
  getScoutMissions() =>
      (super.noSuchMethod(
            Invocation.method(#getScoutMissions, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i11.MissionEntity>>(
                    this,
                    Invocation.method(#getScoutMissions, []),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.value(
                  _FakeEither_0<_i7.ApiFail, List<_i11.MissionEntity>>(
                    this,
                    Invocation.method(#getScoutMissions, []),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>);

  @override
  _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>
  watchNearbyMissions(_i12.NearbyMissionsInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#watchNearbyMissions, [input]),
            returnValue:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
            returnValueForMissingStub:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
          )
          as _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, void>> acceptMission(
    _i12.AcceptMissionInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptMission, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
              _FakeEither_0<_i7.ApiFail, void>(
                this,
                Invocation.method(#acceptMission, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
                  _FakeEither_0<_i7.ApiFail, void>(
                    this,
                    Invocation.method(#acceptMission, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, void>>);

  @override
  _i6.Stream<_i2.Either<_i7.ApiFail, _i11.MissionEntity?>> watchActiveMission(
    _i12.WatchActiveMissionInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveMission, [input]),
            returnValue:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, _i11.MissionEntity?>
                >.empty(),
            returnValueForMissingStub:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, _i11.MissionEntity?>
                >.empty(),
          )
          as _i6.Stream<_i2.Either<_i7.ApiFail, _i11.MissionEntity?>>);

  @override
  _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>
  watchScoutRequests(_i12.WatchActiveMissionInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#watchScoutRequests, [input]),
            returnValue:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
            returnValueForMissingStub:
                _i6.Stream<
                  _i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>
                >.empty(),
          )
          as _i6.Stream<_i2.Either<_i7.ApiFail, List<_i11.MissionEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, void>> updateMissionStatus(
    _i12.UpdateMissionStatusInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMissionStatus, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
              _FakeEither_0<_i7.ApiFail, void>(
                this,
                Invocation.method(#updateMissionStatus, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
                  _FakeEither_0<_i7.ApiFail, void>(
                    this,
                    Invocation.method(#updateMissionStatus, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, void>>);

  @override
  _i6.Future<_i2.Either<_i7.ApiFail, void>> declineMission(
    _i12.DeclineMissionInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#declineMission, [input]),
            returnValue: _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
              _FakeEither_0<_i7.ApiFail, void>(
                this,
                Invocation.method(#declineMission, [input]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.Either<_i7.ApiFail, void>>.value(
                  _FakeEither_0<_i7.ApiFail, void>(
                    this,
                    Invocation.method(#declineMission, [input]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.ApiFail, void>>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  List<_i16.Profile> get profiles =>
      (super.noSuchMethod(
            Invocation.getter(#profiles),
            returnValue: <_i16.Profile>[],
            returnValueForMissingStub: <_i16.Profile>[],
          )
          as List<_i16.Profile>);
}

/// A class which mocks [MissionEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMissionEntity extends _i1.Mock implements _i11.MissionEntity {
  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);

  @override
  double get price =>
      (super.noSuchMethod(
            Invocation.getter(#price),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int get durationInSec =>
      (super.noSuchMethod(
            Invocation.getter(#durationInSec),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get address =>
      (super.noSuchMethod(
            Invocation.getter(#address),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#address),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#address),
            ),
          )
          as String);

  @override
  _i18.MissionStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i18.MissionStatus.open,
            returnValueForMissingStub: _i18.MissionStatus.open,
          )
          as _i18.MissionStatus);

  @override
  double get mapX =>
      (super.noSuchMethod(
            Invocation.getter(#mapX),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get mapY =>
      (super.noSuchMethod(
            Invocation.getter(#mapY),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  List<_i19.RatingEntity> get ratings =>
      (super.noSuchMethod(
            Invocation.getter(#ratings),
            returnValue: <_i19.RatingEntity>[],
            returnValueForMissingStub: <_i19.RatingEntity>[],
          )
          as List<_i19.RatingEntity>);

  @override
  bool get hasRatedByClient =>
      (super.noSuchMethod(
            Invocation.getter(#hasRatedByClient),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasRatedByScout =>
      (super.noSuchMethod(
            Invocation.getter(#hasRatedByScout),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasRated =>
      (super.noSuchMethod(
            Invocation.getter(#hasRated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMyMission =>
      (super.noSuchMethod(
            Invocation.getter(#isMyMission),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get durationLabel =>
      (super.noSuchMethod(
            Invocation.getter(#durationLabel),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#durationLabel),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#durationLabel),
            ),
          )
          as String);

  @override
  String get formattedPrice =>
      (super.noSuchMethod(
            Invocation.getter(#formattedPrice),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#formattedPrice),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#formattedPrice),
            ),
          )
          as String);
}

/// A class which mocks [NearbyScout].
///
/// See the documentation for Mockito's code generation for more information.
class MockNearbyScout extends _i1.Mock implements _i14.NearbyScout {
  @override
  _i3.User get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUser_1(this, Invocation.getter(#user)),
            returnValueForMissingStub: _FakeUser_1(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i3.User);

  @override
  double get distanceMeters =>
      (super.noSuchMethod(
            Invocation.getter(#distanceMeters),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);
}

/// A class which mocks [RemoteAuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteAuthDatasource extends _i1.Mock
    implements _i20.RemoteAuthDatasource {
  @override
  _i6.Future<_i4.AuthResponse> loginWithPassword({
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithPassword, [], {#data: data}),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#loginWithPassword, [], {#data: data}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#loginWithPassword, [], {#data: data}),
              ),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> verifyOTP({
    required Map<String, dynamic>? data,
    _i4.OtpType? otpType = _i4.OtpType.email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {#data: data, #otpType: otpType}),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#verifyOTP, [], {
                  #data: data,
                  #otpType: otpType,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#verifyOTP, [], {
                  #data: data,
                  #otpType: otpType,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signupWithOAuth({
    required Map<String, dynamic>? data,
    _i4.OAuthProvider? provider = _i4.OAuthProvider.google,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signupWithOAuth, [], {
              #data: data,
              #provider: provider,
            }),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signupWithOAuth, [], {
                  #data: data,
                  #provider: provider,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signupWithOAuth, [], {
                  #data: data,
                  #provider: provider,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signUp({required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {#data: data}),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signUp, [], {#data: data}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#signUp, [], {#data: data}),
              ),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.UserResponse> updatePhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhone, [phone]),
            returnValue: _i6.Future<_i4.UserResponse>.value(
              _FakeUserResponse_3(
                this,
                Invocation.method(#updatePhone, [phone]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UserResponse>.value(
              _FakeUserResponse_3(
                this,
                Invocation.method(#updatePhone, [phone]),
              ),
            ),
          )
          as _i6.Future<_i4.UserResponse>);

  @override
  _i6.Future<Map<String, dynamic>?> updateNames(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateNames, [data]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<Map<String, dynamic>?> updateScoutProfile(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateScoutProfile, [data]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendPasswordResetOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetOtp, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResponse> verifyPasswordResetOtp({
    required String? email,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetOtp, [], {
              #email: email,
              #otp: otp,
            }),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#verifyPasswordResetOtp, [], {
                  #email: email,
                  #otp: otp,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(
                this,
                Invocation.method(#verifyPasswordResetOtp, [], {
                  #email: email,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.UserResponse> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i6.Future<_i4.UserResponse>.value(
              _FakeUserResponse_3(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UserResponse>.value(
              _FakeUserResponse_3(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
          )
          as _i6.Future<_i4.UserResponse>);
}

/// A class which mocks [RemoteMissionsDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteMissionsDatasource extends _i1.Mock
    implements _i21.RemoteMissionsDatasource {
  @override
  _i6.Future<Map<String, dynamic>> postMission(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#postMission, [data]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> createLiveRequest(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLiveRequest, [data]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getNearbyScouts(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyScouts, [data]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMyMissions() =>
      (super.noSuchMethod(
            Invocation.method(#getMyMissions, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Stream<List<Map<String, dynamic>>> watchActiveMissions() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveMissions, []),
            returnValue: _i6.Stream<List<Map<String, dynamic>>>.empty(),
            returnValueForMissingStub:
                _i6.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i6.Stream<List<Map<String, dynamic>>>);

  @override
  _i6.Stream<Map<String, dynamic>> watchLiveSessions(List<String>? missions) =>
      (super.noSuchMethod(
            Invocation.method(#watchLiveSessions, [missions]),
            returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
            returnValueForMissingStub: _i6.Stream<Map<String, dynamic>>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getScoutMissions() =>
      (super.noSuchMethod(
            Invocation.method(#getScoutMissions, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Stream<List<Map<String, dynamic>>> watchNearbyMissions(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchNearbyMissions, [data]),
            returnValue: _i6.Stream<List<Map<String, dynamic>>>.empty(),
            returnValueForMissingStub:
                _i6.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i6.Stream<List<Map<String, dynamic>>>);

  @override
  _i6.Future<bool> acceptMission(String? missionId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptMission, [missionId]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<Map<String, dynamic>?> watchScoutActiveMission(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchScoutActiveMission, [profileId]),
            returnValue: _i6.Stream<Map<String, dynamic>?>.empty(),
            returnValueForMissingStub:
                _i6.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>?>);

  @override
  _i6.Stream<List<Map<String, dynamic>>> watchScoutRequests(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchScoutRequests, [profileId]),
            returnValue: _i6.Stream<List<Map<String, dynamic>>>.empty(),
            returnValueForMissingStub:
                _i6.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i6.Stream<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> updateMissionStatus({
    required String? missionId,
    required Map<String, dynamic>? values,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMissionStatus, [], {
              #missionId: missionId,
              #values: values,
            }),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AuthResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthResponse extends _i1.Mock implements _i4.AuthResponse {}

/// A class which mocks [UserResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserResponse extends _i1.Mock implements _i4.UserResponse {}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i4.Session {
  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get tokenType =>
      (super.noSuchMethod(
            Invocation.getter(#tokenType),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
          )
          as String);

  @override
  _i4.User get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUser_4(this, Invocation.getter(#user)),
            returnValueForMissingStub: _FakeUser_4(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i4.User);

  @override
  bool get isExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isExpired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set expiresAt(int? value) => super.noSuchMethod(
    Invocation.setter(#expiresAt, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.Session copyWith({
    String? accessToken,
    int? expiresIn,
    String? refreshToken,
    String? tokenType,
    String? providerToken,
    String? providerRefreshToken,
    _i4.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            }),
            returnValue: _FakeSession_5(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
            returnValueForMissingStub: _FakeSession_5(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
          )
          as _i4.Session);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupaUser extends _i1.Mock implements _i4.User {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i17.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i17.dummyValue<String>(this, Invocation.getter(#aud)),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#aud),
            ),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
            returnValueForMissingStub: _i17.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
